<a href="https://colab.research.google.com/github/20023173uhi/20023173_DataAnalytics/blob/main/assement_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assesment part 2**

In this part of the excercise, Python is used to train and test linear regressor. The use of linear regressor is a linear approach to modelling the relationship between a scalar response and one or more explanatory variables - dependent and independent variables. It may be considered to be the next step up in modelling from correlation.
The theory of regression analysis has underlying elegant mathematics and a well developed statistical theory going back about two hundred years [REF Montgomery *et.al.*(2012) Introduction to Linear Regression Analysis 4th ed. John Wiley & sons ] but computer models play an importent role in modern regression analysis.   

The data set used in this section of the excercise comes from *part one* of this two part excercise, collating traffic collision & corresponding weather variables from New York City. The methods of obtaining, cleaning and checking this data set can be found in "assesment part1" and fitting with the requiremnts of this type of model, efforts have been made to retain as much of the data as possible [Molnar, C. (2020) Interpretable Machine Learning. Leanpub.]  

Note - Now working in Python rather than R. 

In [ ]:
import pandas as pd  #for data analysis and manipulation tools
import numpy as np  #support for large, multi-dimensional arrays and matrices  
                    #and high-level mathematical functions to operate on these arrays



In [ ]:
collisiondf = pd.read_csv( 'https://raw.githubusercontent.com/20023173uhi/20023173_DataAnalytics/main/collisionsdnn.csv', index_col=0,) #import csv from part one of assesment
print(collisiondf) # to check   
SCALE = 800

      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
1       1    0    0    0     0  ...    6.5  0.00  32.95   3.3         523
2       0    1    0    0     0  ...    9.5  0.01  48.45   9.2         473
3       0    0    0    0     0  ...   10.0  0.00  33.55   8.0         402
4       0    0    0    0     0  ...    8.2  0.02  43.10   5.4         506
5       0    0    0    0     1  ...   10.0  0.00  29.45   9.4         522
...   ...  ...  ...  ...   ...  ...    ...   ...    ...   ...         ...
2725    1    0    0    0     0  ...    7.1  0.56  47.45   9.4         751
2726    1    0    0    0     0  ...   10.0  0.00  17.95  17.8         792
2727    0    0    0    0     1  ...    6.0  0.84  42.55  12.4         525
2728    0    0    0    1     0  ...    8.0  1.96  44.55  25.0         493
2729    0    0    0    1     0  ...    8.8  1.90  36.75  11.9         411

[2729 rows x 27 columns]



Introducing a random selection of part of the data - this is done by use of a combination of iloc( integer-location based indexing for selection by position) and random number sequence which is based upon the length of the dataset used. 

In [ ]:
shuffled_df = collisiondf.iloc [np.random.permutation(len(collisiondf))] 
print(shuffled_df[:10]) # no longer from 1 > 2729, but now using a random index

      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
1389    0    0    0    0     0  ...    4.2  0.00  72.50   7.6         747
116     0    0    0    0     0  ...    4.4  0.03  42.60  12.4         497
1395    1    0    0    0     0  ...   10.0  0.00  71.10   7.5         490
1852    0    0    0    1     0  ...    9.0  0.22  63.70   6.4         480
2453    0    0    0    0     0  ...   10.0  0.00  38.50  15.1         765
355     0    1    0    0     0  ...   10.0  0.02  37.50  14.4         567
154     1    0    0    0     0  ...   10.0  0.00  26.50  14.4         677
994     0    1    0    0     0  ...   10.0  0.03  62.00   9.6         652
1578    1    0    0    0     0  ...    9.0  0.01  66.45   5.3         667
1530    0    0    0    0     0  ...    5.1  0.02  69.95  12.3         569

[10 rows x 27 columns]


Now that the data has been imported and shuffled, prior to running the model, a section of data should be removed, and this data can then be used to test the model after training.

For this purpose, the first 100 rows of the shuffled dataframe are cut from the dataframe.
This value of 100 was arbitarily chosen as likely to produce enough values for each of the seven days of the week, but not large enough to have an effect upon the size of the data used to train the model.
    
 

In [ ]:
num_model_testings_rows = 100  # the rowns held back for later testing
model_testing_df = shuffled_df.head(num_model_testings_rows)
print(model_testing_df)

      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
1389    0    0    0    0     0  ...    4.2  0.00  72.50   7.6         747
116     0    0    0    0     0  ...    4.4  0.03  42.60  12.4         497
1395    1    0    0    0     0  ...   10.0  0.00  71.10   7.5         490
1852    0    0    0    1     0  ...    9.0  0.22  63.70   6.4         480
2453    0    0    0    0     0  ...   10.0  0.00  38.50  15.1         765
...   ...  ...  ...  ...   ...  ...    ...   ...    ...   ...         ...
803     0    0    1    0     0  ...    5.6  0.13  61.00   9.3         649
1729    0    0    0    0     0  ...   10.0  0.01  71.70   4.7         550
1551    0    0    0    1     0  ...    9.8  0.01  69.45   4.6         512
933     1    0    0    0     0  ...    6.7  0.02  63.05   9.0         736
846     0    0    0    0     0  ...    1.9  0.70  48.05  14.7         606

[100 rows x 27 columns]


In [ ]:
shuffled_df = shuffled_df[num_model_testings_rows:] # reducing the dataframe by these retained rows above 
print(shuffled_df) # check that the data frame is reduced from the orginal 2729 by the required no.



      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
2228    0    0    1    0     0  ...   10.0  0.00  59.45  13.2         556
2112    0    0    1    0     0  ...    7.0  0.01  66.00   5.2         500
745     0    0    0    1     0  ...   10.0  0.24  43.95  11.7         471
1316    0    0    0    0     0  ...    9.9  0.00  75.45   5.6         609
23      0    0    0    0     0  ...    2.6  0.08  35.25   4.9         542
...   ...  ...  ...  ...   ...  ...    ...   ...    ...   ...         ...
627     0    0    1    0     0  ...   10.0  0.02  38.50  15.9         488
465     0    0    0    1     0  ...   10.0  0.00  32.00   3.1         500
1359    1    0    0    0     0  ...   10.0  0.02  66.45   8.5         685
599     0    0    1    0     0  ...    7.8  0.24  36.40  12.7         459
43      0    0    0    0     0  ...   10.0  0.00  32.00   7.9         495

[2629 rows x 27 columns]


In order to model for a selection of variables, the "predictors" specified below are selected form the dataset using their column. For each combination of variables used, the model saved is renamed accordingly  

In [ ]:
#predictors = shuffled_df.iloc[:,0:26] # all columns apart from the collsions  checked
#predictors = shuffled_df.iloc[ :,[1,2,3,4,5,6,7,21,22] ] # with dewp & pressr and days checked
#redictors = shuffled_df.iloc [:, [0,1,2,3,4,5,6,21] ] # with pressure checked
#predictors = shuffled_df.iloc [:, [0,1,2,3,4,5,6,22,23] ] # with visb and prcp checked
#predictors = shuffled_df.iloc [:, [0,1,2,3,4,5,6,22 ] ]# with visb checked
#predictors = shuffled_df.iloc [:, [0,1,2,3,4,5,6] ] # juat the days
#predictors = shuffled_df.iloc [:, [0,1,2,3,4,5,6, 23] ] # with prec  
#predictors = shuffled_df.iloc [:, [0,1,2,3,4,5,6, 24] ] # temp
predictors = shuffled_df.iloc [:, [0,1,2,3,4,5,6, 25] ] # wind speed

print(predictors[:6]) # taking a look at first 6 rows for each new variable selection

      Fri  Mon  Sat  Sun  Thur  Tue  Wed  wdsp
2228    0    0    1    0     0    0    0  13.2
2112    0    0    1    0     0    0    0   5.2
745     0    0    0    1     0    0    0  11.7
1316    0    0    0    0     0    0    1   5.6
23      0    0    0    0     0    1    0   4.9
1663    0    0    0    1     0    0    0   9.9


In [ ]:
print(predictors.values)

[[ 0.   0.   1.  ...  0.   0.  13.2]
 [ 0.   0.   1.  ...  0.   0.   5.2]
 [ 0.   0.   0.  ...  0.   0.  11.7]
 ...
 [ 1.   0.   0.  ...  0.   0.   8.5]
 [ 0.   0.   1.  ...  0.   0.  12.7]
 [ 0.   0.   0.  ...  0.   1.   7.9]]


The single target variable used in this model is the daily number of collsions.



In [ ]:
target = shuffled_df.iloc[:,26] # selecting the collisions column
print(target[:10]/SCALE) # checking 

2228    0.69500
2112    0.62500
745     0.58875
1316    0.76125
23      0.67750
1663    0.67500
612     0.72250
1681    0.73375
1043    0.85750
2177    0.64375
Name: collisions, dtype: float64


In [ ]:
# to split the previously shuffled data into a training set
training_set = int(len(shuffled_df['collisions'])*0.8) # cast to int.
testing_set = len(shuffled_df['collisions']) - training_set



In [ ]:
num_predictors = len(predictors) #number of imput values
print(num_predictors) # to check 
num_target = 1  
print(num_target) # checking 

2629
1


In [ ]:
#importing tensorflow for numerical computing.
%tensorflow_version 1.x  # to allow use of deprecated method 
import tensorflow as tf #main object that is passed in tf.Tensor

import shutil # module offers high-level operations on files and collections of files
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.INFO) # logging for tensorflow

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `1.x  # to allow use of deprecated method`. This will be interpreted as: `1.x`.


TensorFlow 1.x selected.


In [ ]:
shutil.rmtree('/tmp/linear_regression_trained_model_windspeed',ignore_errors= True ) #saving model re. predictors selected above

In [ ]:
estimator = tf.contrib.learn.SKCompat(
    tf.contrib.learn.LinearRegressor(
        model_dir = '/tmp/linear_regression_trained_model_windspeed',
        optimizer=tf.train.AdamOptimizer(learning_rate = 0.5)
        , enable_centered_bias=False, 
        feature_columns=tf.contrib.learn.infer_real_valued_columns_from_input(predictors.values)))


The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Instructions for updating:
Please specify feature columns explicitly.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please access pandas data directly.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please convert numpy dtypes explicitly.
Instructions for updating:
Please specify feature columns explicitly.
Instructions for updating:
Please switch to tf.contrib.estimator.*_head.
Instructions for updating:
Please replace uses of any Estimator from tf.contrib.learn with an Estimator from tf.estimator.*
Instructions for updating:


In [ ]:
#print("starting to train ");

In [ ]:
#estimator.fit(predictors[:trainsize].values, targets[:trainsize].values.reshape(trainsize, noutputs)/SCALE_NUM_TRIPS, steps=10000)
print(target[:training_set].values.reshape(training_set,num_target)/SCALE)

try:
  estimator.fit(predictors[:training_set].values, target[:training_set].values.reshape(training_set,num_target)/SCALE, steps = 10000)
except Exception as e:
  print(f"oops{e}")

[[0.695  ]
 [0.625  ]
 [0.58875]
 ...
 [0.9875 ]
 [0.8875 ]
 [0.8    ]]
Instructions for updating:
Please access pandas data directly.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.EstimatorSpec. You can use the `estimator_spec` method to create an equivalent one.
INFO:tensorflow:Create CheckpointSaverHook.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/linear_regression_trained_model_windspeed/model.ckpt.
INFO:tensorflow:loss = 0.5433829, step = 1
INFO:tensorflow:global_step/sec: 594.527
INFO:tensorflow:loss = 0.008648841, step = 101 (0.173 sec)
INFO:tensorflow:global_step/sec: 701.5

In [ ]:

preds = estimator.predict(x=predictors[training_set:].values) #check predictions based on predictors. nb, this gives warnings are consided acceptable

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/linear_regression_trained_model_windspeed/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [ ]:
# Apply the Scale value to the outputs (as defined above )
predslistscale = preds['scores']*SCALE
print(predslistscale) # checking

[567.8384  560.0125  439.95572 551.37384 417.94962 569.229   553.93225
 439.26044 589.91077 532.6005  442.28543 421.7264  551.37384 441.89038
 462.74963 490.01794 448.84348 450.92935 597.55914 483.23364 448.54315
 337.9892  550.4557  553.4597  585.22107 571.83276 603.12164 516.38556
 440.8948  447.60413 548.5926  399.8716  546.2838  594.0826  412.6874
 582.2623  556.241   591.30133 525.42456 621.89496 329.94574 484.32797
 420.48712 475.28897 626.0668  463.59625 453.41034 463.83997 614.2466
 496.44452 634.41046 428.1355  432.5511  466.62122 431.1605  570.4421
 596.86383 511.04593 466.22614 526.81525 488.57327 568.7566  599.645
 456.49185 558.10406 584.34827 540.64795 592.692   485.02332 507.3466
 547.89734 591.30133 477.74615 484.32797 554.6275  464.93277 451.6247
 473.20303 588.52014 568.3562  530.2183  600.3404  427.44016 582.4399
 545.116   578.26807 371.66425 396.      559.3172  408.51556 548.3698
 504.7882  482.242   549.7604  461.75403 448.99472 419.34024 535.15894
 570.4421  403.

In [ ]:
rmse = np.sqrt(np.mean((target[training_set:].values - predslistscale)**2))
print('LinearRegression has RMSE of {0}'.format(rmse)); # root-mean-square error (RMSE) is a frequently used measure of differences between values

LinearRegression has RMSE of 134.5742595937697


In [ ]:
avg = np.mean(shuffled_df['collisions'] [:training_set] )  # to get mean of collisions

In [ ]:
# now to calculate the RMSE this uses the collisions and the mean of all target values
rmse = np.sqrt(np.mean(( shuffled_df['collisions'][training_set:]- avg)**2))
print('Using average = {0} has RMSE of {1}'.format(avg, rmse));

Using average = 591.4412743699477 has RMSE of 93.15178767428614


Now that the model has been built and tested, the next step is to take some of the data that was retained from the original dataset.

As seen above, in order to introduce a randomness into the selection of data retained for this purpose, the original collisions dataset had been shuffled before  *model_testing_df*  was selected. 

As this data has not been used in the model training, the required data can be obtained to input into the model to check fit fit.  

 


In [ ]:
print(model_testing_df)  # the 100 rows removed from the dataset before building the model


      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
1389    0    0    0    0     0  ...    4.2  0.00  72.50   7.6         747
116     0    0    0    0     0  ...    4.4  0.03  42.60  12.4         497
1395    1    0    0    0     0  ...   10.0  0.00  71.10   7.5         490
1852    0    0    0    1     0  ...    9.0  0.22  63.70   6.4         480
2453    0    0    0    0     0  ...   10.0  0.00  38.50  15.1         765
...   ...  ...  ...  ...   ...  ...    ...   ...    ...   ...         ...
803     0    0    1    0     0  ...    5.6  0.13  61.00   9.3         649
1729    0    0    0    0     0  ...   10.0  0.01  71.70   4.7         550
1551    0    0    0    1     0  ...    9.8  0.01  69.45   4.6         512
933     1    0    0    0     0  ...    6.7  0.02  63.05   9.0         736
846     0    0    0    0     0  ...    1.9  0.70  48.05  14.7         606

[100 rows x 27 columns]


Now the rows of retained data can been subdevided by each day of the week to use for testing and data for each day can be checked by print. 
Although the distribution of data across the days is random, it is to be expected that the spread will be even enough to produce enough values for each day of the week.        

In [ ]:
# Sunday data for testing
sun_model_testing_df = model_testing_df[(model_testing_df.Sun ==1)]
print(sun_model_testing_df)

      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
1852    0    0    0    1     0  ...    9.0  0.22  63.70   6.4         480
2297    0    0    0    1     0  ...   10.0  0.00  45.95   7.5         479
827     0    0    0    1     0  ...   10.0  0.26  52.10  13.4         448
2558    0    0    0    1     0  ...   10.0  0.00  36.05   7.5         409
389     0    0    0    1     0  ...   10.0  0.00  36.95  16.6         509
1788    0    0    0    1     0  ...   10.0  0.00  66.50  13.6         482
2443    0    0    0    1     0  ...    8.8  0.05  51.10  12.0         415
1509    0    0    0    1     0  ...    9.3  0.00  70.50  10.1         512
2250    0    0    0    1     0  ...   10.0  0.01  53.95  13.8         512
964     0    0    0    1     0  ...   10.0  0.00  52.00   6.8         618
2475    0    0    0    1     0  ...    5.5  0.13  45.50  14.4         529
2423    0    0    0    1     0  ...   10.0  0.00  55.90  11.0         472
1032    0    0    0    1     0  ...   

In [ ]:
#Monday data for testing 
mon_model_testing_df = model_testing_df[(model_testing_df.Mon ==1)]
print(mon_model_testing_df )

      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
355     0    1    0    0     0  ...   10.0  0.02  37.50  14.4         567
994     0    1    0    0     0  ...   10.0  0.03  62.00   9.6         652
68      0    1    0    0     0  ...   10.0  0.00  32.00   6.2         477
2450    0    1    0    0     0  ...   10.0  0.40  49.45  12.8         641
986     0    1    0    0     0  ...    9.6  0.00  57.05  10.3         433
354     0    1    0    0     0  ...   10.0  0.00  47.50  11.7         428
294     0    1    0    0     0  ...    6.5  0.72  42.95  10.7         557
2163    0    1    0    0     0  ...   10.0  0.36  44.00  11.7         650
2209    0    1    0    0     0  ...    9.4  0.00  66.05   4.5         607
2015    0    1    0    0     0  ...    8.2  0.11  66.50  12.3         662
2517    0    1    0    0     0  ...    6.7  0.00  53.50   7.9         637

[11 rows x 27 columns]


In [ ]:
#Tuesday data for testing
tue_model_testing_df = model_testing_df[(model_testing_df.Tue ==1)]
print(tue_model_testing_df )

      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
2453    0    0    0    0     0  ...   10.0  0.00  38.50  15.1         765
1831    0    0    0    0     0  ...    8.7  0.22  70.50   5.6         619
434     0    0    0    0     0  ...   10.0  0.00  29.85  15.1         688
346     0    0    0    0     0  ...   10.0  0.14  31.00   9.7         613
2533    0    0    0    0     0  ...    7.3  0.20  37.50   7.3         700
561     0    0    0    0     0  ...   10.0  0.00  38.45  10.8         610
1149    0    0    0    0     0  ...    3.1  0.07  61.60   4.9         613
2497    0    0    0    0     0  ...    9.6  0.00  40.55   4.2         645
1080    0    0    0    0     0  ...    2.2  0.00  52.55  14.5         743
51      0    0    0    0     0  ...   10.0  0.00  34.95   7.9         637
1207    0    0    0    0     0  ...    7.5  0.34  61.60   8.7         613
1981    0    0    0    0     0  ...    7.6  0.11  66.20   5.5         556
1803    0    0    0    0     0  ...   

In [ ]:
#Wednesday data for testing
wed_model_testing_df = model_testing_df[(model_testing_df.Wed ==1)]
print(wed_model_testing_df )

      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
1389    0    0    0    0     0  ...    4.2  0.00  72.50   7.6         747
116     0    0    0    0     0  ...    4.4  0.03  42.60  12.4         497
1530    0    0    0    0     0  ...    5.1  0.02  69.95  12.3         569
1766    0    0    0    0     0  ...    6.3  0.00  73.05  12.4         629
1674    0    0    0    0     0  ...    7.2  1.01  70.50   7.9         643
2644    0    0    0    0     0  ...    9.1  0.01  48.90   6.3         514
1549    0    0    0    0     0  ...    9.8  0.00  70.55   1.7         504
265     0    0    0    0     0  ...   10.0  0.00  26.95   7.6         585
148     0    0    0    0     0  ...    7.0  0.35  42.10   8.8         578
1629    0    0    0    0     0  ...   10.0  0.00  70.00   8.5         635
209     0    0    0    0     0  ...    8.8  0.39  36.05  15.1         630
1694    0    0    0    0     0  ...    9.2  0.30  74.50   7.4         606
1876    0    0    0    0     0  ...   

In [ ]:
#Thursday data for testing
thu_model_testing_df = model_testing_df[(model_testing_df.Thur ==1)]
print(thu_model_testing_df )

      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
1666    0    0    0    0     1  ...    8.6  0.00  69.45   8.5         560
552     0    0    0    0     1  ...    9.7  0.49  37.05  10.4         557
2213    0    0    0    0     1  ...    8.4  0.00  61.55  15.8         657
658     0    0    0    0     1  ...    8.2  0.79  40.00  15.8         633
1392    0    0    0    0     1  ...   10.0  0.00  63.50   7.3         610
2646    0    0    0    0     1  ...   10.0  0.01  36.50   3.6         620
1208    0    0    0    0     1  ...   10.0  0.00  60.50   8.7         534
2335    0    0    0    0     1  ...   10.0  0.00  48.05   3.4         384

[8 rows x 27 columns]


In [ ]:
#Friday data for testing
fri_model_testing_df = model_testing_df[(model_testing_df.Fri ==1)]
print(fri_model_testing_df )
                       
                               

      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
1395    1    0    0    0     0  ...   10.0  0.00  71.10   7.5         490
154     1    0    0    0     0  ...   10.0  0.00  26.50  14.4         677
1578    1    0    0    0     0  ...    9.0  0.01  66.45   5.3         667
462     1    0    0    0     0  ...    9.5  0.00  39.45  10.8         673
1044    1    0    0    0     0  ...    9.4  0.00  47.00  13.8         660
2340    1    0    0    0     0  ...    9.8  0.00  49.50  11.0         621
2548    1    0    0    0     0  ...   10.0  0.04  37.60   8.2         687
216     1    0    0    0     0  ...   10.0  0.04  35.95  24.0         565
21      1    0    0    0     0  ...   10.0  0.00  41.00   4.3         605
590     1    0    0    0     0  ...    5.1  0.44  43.40  13.1         532
2194    1    0    0    0     0  ...   10.0  0.00  59.95  13.3         621
1691    1    0    0    0     0  ...   10.0  0.19  68.00   7.4         601
1413    1    0    0    0     0  ...   

In [ ]:
#Saturday data for testing
sat_model_testing_df = model_testing_df[(model_testing_df.Sat ==1)]
print(sat_model_testing_df )

      Fri  Mon  Sat  Sun  Thur  ...  visib  prcp   temp  wdsp  collisions
430     0    0    1    0     0  ...    7.3  0.02  33.50  11.8         516
2107    0    0    1    0     0  ...   10.0  0.00  53.05  10.9         586
2311    0    0    1    0     0  ...    7.9  0.00  47.50   2.0         444
1074    0    0    1    0     0  ...   10.0  0.00  48.50  13.7         580
1155    0    0    1    0     0  ...   10.0  0.00  64.05   8.0         688
292     0    0    1    0     0  ...    9.0  0.00  34.95  11.3         549
2667    0    0    1    0     0  ...   10.0  0.03  37.95  12.9         566
767     0    0    1    0     0  ...    9.2  0.07  48.05  10.3         587
803     0    0    1    0     0  ...    5.6  0.13  61.00   9.3         649

[9 rows x 27 columns]


Now that the day specific data that was retained has been isolated, this can now be used to check for each specfic day.

In [ ]:
input = sun_model_testing_df [:3]
print(len(input["Sun"])) # to examine df


#for just windspeed and day
input = mon_model_testing_df.iloc [:, [0,1,2,3,4,5,6, 25] ] 
print(len(input["Mon"]))


3
11


Having run the different models for individual days, being satisfied that the model functions in the way that was anticipated, the next stage is to develop  method to take a list of each of the days individually, and run through them in turn, returning the results for each day in turn.      

In [ ]:
seven_days = ( sun_model_testing_df, mon_model_testing_df,tue_model_testing_df,wed_model_testing_df, thu_model_testing_df, fri_model_testing_df,sat_model_testing_df)
#print (seven_days) 

############################  this is where I stopped #####################################




In [ ]:
estimator = tf.contrib.learn.SKCompat(tf.contrib.learn.LinearRegressor(model_dir= '/tmp/linear_regression_trained_model_windspeed', enable_centered_bias=False, 
                                                                       feature_columns=tf.contrib.learn.infer_real_valued_columns_from_input(input.values)))

preds = estimator.predict(x= input.values)

# number of collisions based upon the value of 800 from assessemnt part1
predslistnorm = preds['scores']
predslistscale = preds['scores']*800
print(predslistnorm)
prednorm = format(str(predslistnorm))
pred = format(str(predslistscale))
print(prednorm)
print(pred)
 

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7effe0e1ca90>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute': None, '_eval_distribute': None, '_experimental_max_worker_delay_secs': None, '_device_fn': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_protocol': None, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/linear_regression_trained_model_windspeed', '_session_creation_timeout_secs': 7200}
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/linear_regression_trained_mode